# Load the libraries
```{r}
library(here)
library(tidyverse)
library(sf)
library(stars)
library(tmap)
```

# Load the data
```{r}
ej_screen <- sf::st_read(here::here("data", "ejscreen", "EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb")) 

```

# Filter the data to California
# Filter the data to Santa Cruz County, San Mateo County
```{r}
california <- ej_screen %>%
  dplyr::filter(ST_ABBREV == "CA")

santa_cruz<- california %>%
  dplyr::filter(CNTY_NAME %in% c("Santa Cruz County"))

san_mateo <- california %>%
    dplyr::filter(CNTY_NAME %in% c("San Mateo County"))

santa_clara <- california %>%
  dplyr::filter(CNTY_NAME %in% c("Santa Clara County"))
```

# Build maps and label maps with PM2.5
```{r}
tm_shape(santa_cruz)+
    tm_borders()+
    tm_fill("PM25")+
    tm_layout(main.title = "Santa Cruz County")+
tm_compass(position = c('right', 'top'))+
tm_scalebar()

tm_shape(san_mateo)+
    tm_borders()+
    tm_fill("PM25") +
    tm_layout(main.title = "San Mateo County")+
    tm_compass(position = c('right', 'top'))+
    tm_scalebar()
```


